"""Loader for EGYSpeak (MohamedGomaa30/EGYSpeak) - pseudo-labelled, fail closed.

Governance (verified 2026-09-20 by the orchestrator from the live dataset card):

- Public, ungated; 147,979 rows; fields ``file_name``/``transcription``.
- ~22.4 GB audio in 23 tar shards; 16 kHz mono PCM.
- Machine transcripts generated by EgypTalk-ASR-v2 and filtered: ALWAYS
  pseudo-labelled, never gold.
- Card says CC-BY-4.0, but upstream Kaggle ``fadisarwat/egyptian-arabic-lines``
  version 5 is GPL-3.0: unresolved license-source conflict. ``release_blocker``.

Because of the unresolved license chain this loader FAILS CLOSED:

- Metadata inspection (counts/rows, no tar extraction, no full audio download)
  is allowed.
- Full audio use requires an explicit ``allow_full_audio=True`` opt-in AND
  ``allow_license_use=True``; without both, any audio request raises.
"""

from __future__ import annotations

from collections.abc import Iterable, Iterator
from typing import Any

from masricx.data.loader_utils import (
    load_datasets_module,
    require_revision,
    stable_sample_id,
)

__all__ = [
    "EGYSPEAK_LICENSE_CONFLICT",
    "EGYSPEAK_REPO_ID",
    "EGYSPEAK_REVISION",
    "load_egyspeak_examples",
    "load_egyspeak_streaming",
]

EGYSPEAK_REPO_ID = "MohamedGomaa30/EGYSpeak"
EGYSPEAK_REVISION = "59c40fc6833382a743c180f50addcda5edaa47c3"
EGYSPEAK_LICENSE_CONFLICT = (
    "EGYSpeak card declares CC-BY-4.0 but upstream Kaggle "
    "fadisarwat/egyptian-arabic-lines v5 is GPL-3.0; release blocked pending "
    "license-chain resolution."
)


def load_egyspeak_examples(
    revision: str = EGYSPEAK_REVISION,
    split: str = "train",
    config: str | None = None,
    streaming: bool = False,
    max_examples: int | None = None,
    allow_full_audio: bool = False,
    allow_license_use: bool = False,
) -> Iterable[dict[str, Any]]:
    """Yield EGYSpeak examples.

    Audio/full use requires explicit opt-in (``allow_full_audio=True``) and an
    explicit license-review acceptance (``allow_license_use=True``). The audio
    field is otherwise stripped and marked unavailable. Metadata rows are
    inspectable without extracting tar shards (e.g. streaming metadata reads).
    """
    rev = require_revision(EGYSPEAK_REPO_ID, revision)
    audio_requested = allow_full_audio or allow_license_use
    if audio_requested and not (allow_full_audio and allow_license_use):
        raise PermissionError(
            "EGYSpeak audio/full use is fail-closed by default: the license "
            "chain (card CC-BY-4.0 vs upstream Kaggle GPL-3.0) is unresolved. "
            "Pass allow_full_audio=True AND allow_license_use=True only after "
            "the orchestrator resolves the conflict. Metadata inspection stays "
            "allowed. Details: " + EGYSPEAK_LICENSE_CONFLICT
        )
    if max_examples is not None and max_examples < 0:
        raise ValueError(f"max_examples must be >= 0 or None, got {max_examples}")
    datasets = load_datasets_module()
    kwargs: dict[str, Any] = {"revision": rev}
    if config is not None:
        kwargs["name"] = config
    if streaming or max_examples is not None:
        ds = datasets.load_dataset(EGYSPEAK_REPO_ID, split=split, streaming=True, **kwargs)
        iterator: Iterator[dict[str, Any]] = iter(ds)
        for index, example in enumerate(iterator):
            if max_examples is not None and index >= max_examples:
                break
            yield _wrap(EGYSPEAK_REPO_ID, rev, split, index, example, allow_full_audio)
    else:
        ds = datasets.load_dataset(EGYSPEAK_REPO_ID, split=split, **kwargs)
        for index, example in enumerate(ds):
            yield _wrap(EGYSPEAK_REPO_ID, rev, split, index, dict(example), allow_full_audio)


def load_egyspeak_streaming(
    revision: str = EGYSPEAK_REVISION,
    split: str = "train",
    max_examples: int | None = None,
) -> Iterable[dict[str, Any]]:
    """Streaming metadata-safe variant (audio always stripped; fail-closed)."""
    return load_egyspeak_examples(
        revision=revision,
        split=split,
        streaming=True,
        max_examples=max_examples,
        allow_full_audio=False,
        allow_license_use=False,
    )


def _wrap(
    repo_id: str,
    revision: str,
    split: str,
    index: int,
    example: dict[str, Any],
    allow_full_audio: bool,
) -> dict[str, Any]:
    transcript = example.get("transcription")
    audio = example.get("audio") if allow_full_audio else None
    return {
        "sample_id": stable_sample_id(repo_id, revision, split, index),
        "repo_id": repo_id,
        "revision": revision,
        "split": split,
        "index": index,
        "audio": audio,
        "transcript": transcript,
        "file_name": example.get("file_name"),
        "is_pseudo_labelled": True,
        "audio_allowed": allow_full_audio,
    }
