"""Scalable near-duplicate detection over normalized transcripts.

Method (fully documented, including its limits):

- Exact duplicates collapse via a hash map over normalized text.
- Near-duplicate *candidates* are generated by indexing the character-bigram
  hashes of each normalized text: two texts become candidate pairs only if
  they share at least one bigram whose bucket is small enough to be
  informative (see ``_MAX_BUCKET_MEMBERS``). Buckets larger than the cap
  (ultra-common bigrams such as "th" or "e ") are skipped: they are
  uninformative and comparing them would be quadratic.
- For candidate pairs, Jaccard similarity over character-bigram sets is used
  as the estimate. Pairs with similarity >= 0.90 are reported. Reported pairs
  are Jaccard-verified, so they are not false positives.

Worst-case bound (explicit, not "subquadratic by nature"):

- Only buckets with at most ``_MAX_BUCKET_MEMBERS`` members are analyzed;
  each such bucket costs at most ``C(n, 2) <= C(_MAX_BUCKET_MEMBERS, 2)``
  comparisons, so per-bucket work is strictly capped.
- Globally, the total number of Jaccard comparisons is hard-capped at
  ``MAX_TOTAL_COMPARISONS``. Once the budget is exhausted, remaining
  candidates are skipped deterministically (buckets iterated in sorted key
  order) and ``comparison_budget_exhausted`` is reported in the summary.
- The method is therefore NOT mathematically subquadratic in the number of
  indexed texts and NOT exhaustive: it can miss true high-similarity pairs
  whose every shared bigram falls into an oversized (over-cap) bucket. This
  false-negative possibility is inherent to the candidate generation and
  documented here; it is acceptable for audit purposes.

Results are fully deterministic (stable SHA-256 bigram hashes, sorted bucket
order, id-independent canonical pair orientation, sorted output) and
idempotent: analysis does not consume shared state, so repeated
``near_duplicate_pairs()``/``summary()`` calls return identical results.

Texts shorter than ``MIN_NEAR_DUP_CHARS`` (10 normalized chars) are never
candidates. Distinct normalized texts only.
"""

from __future__ import annotations

import hashlib
from collections import Counter
from dataclasses import dataclass, field

__all__ = [
    "MAX_BUCKET_MEMBERS",
    "MAX_NEAR_DUP_PAIRS_REPORTED",
    "MAX_TOTAL_COMPARISONS",
    "MIN_NEAR_DUP_CHARS",
    "NEAR_DUP_SIMILARITY_THRESHOLD",
    "NearDuplicateIndex",
    "TextIndexEntry",
    "bigrams",
    "jaccard_bigrams",
]

NEAR_DUP_SIMILARITY_THRESHOLD = 0.90
MIN_NEAR_DUP_CHARS = 10
MAX_NEAR_DUP_PAIRS_REPORTED = 20

# Explicit worst-case bound parameters.
MAX_BUCKET_MEMBERS = 64  # buckets larger than this are skipped as uninformative
MAX_TOTAL_COMPARISONS = 2_000_000  # global Jaccard-comparison budget


def _stable_hash(payload: str) -> int:
    return int.from_bytes(hashlib.sha256(payload.encode("utf-8")).digest()[:8], "big")


def bigrams(text: str) -> set[str]:
    if len(text) < 2:
        return set()
    return {text[i : i + 2] for i in range(len(text) - 1)}


def jaccard_bigrams(a: str, b: str) -> float:
    A, B = bigrams(a), bigrams(b)
    if not A and not B:
        return 1.0
    union = A | B
    if not union:
        return 0.0
    return len(A & B) / len(union)


@dataclass
class TextIndexEntry:
    sample_id: str
    normalized: str


@dataclass
class NearDuplicateIndex:
    """Accumulates normalized texts with bounded retained state (no waveforms).

    Retains: normalized text per unique entry (needed for Jaccard),
    bigram-hash buckets, and exact-duplicate counts. Bucket keys hashed to
    ints keep the mapping compact.
    """

    entries: list[TextIndexEntry] = field(default_factory=list)
    _by_norm: dict[str, int] = field(default_factory=dict)
    exact_counts: Counter[str] = field(default_factory=Counter)
    _buckets: dict[int, list[int]] = field(default_factory=dict)
    comparisons: int = 0

    def add(self, sample_id: str, normalized: str) -> None:
        if not normalized:
            return
        self.exact_counts[normalized] += 1
        if normalized in self._by_norm:
            return
        if len(normalized) < MIN_NEAR_DUP_CHARS:
            return
        idx = len(self.entries)
        self.entries.append(TextIndexEntry(sample_id, normalized))
        self._by_norm[normalized] = idx
        for bg in bigrams(normalized):
            self._buckets.setdefault(_stable_hash(bg), []).append(idx)

    def near_duplicate_pairs(self) -> list[tuple[str, str, float]]:
        """Deterministic near-duplicate pairs (id_a, id_b, similarity).

        Pure function of current index contents: calling it twice returns
        identical results without consuming any budget twice. Enumeration is
        insertion-order independent (buckets sorted by key, members sorted
        by canonical sample_id), including when the comparison budget is
        exhausted.
        """
        pairs, _ = self._analyze()
        return pairs

    def _analyze(self) -> tuple[list[tuple[str, str, float]], int]:
        """One deterministic bounded analysis pass.

        Candidate order: buckets in sorted key order; members inside each
        bucket are processed in canonical stable-identity order (sorted by
        sample_id), so enumeration - and therefore which pairs the budget
        covers if MAX_TOTAL_COMPARISONS is exhausted - is independent of
        insertion order. Pair results are canonicalized by sample_id.
        Returns (pairs, comparisons_used).
        """
        results: list[tuple[str, str, float]] = []
        seen_pairs: set[tuple[str, str]] = set()
        comparisons = 0
        for key in sorted(self._buckets):
            members = self._buckets[key]
            if len(members) > MAX_BUCKET_MEMBERS:
                continue  # ultra-common bigram: uninformative, capped out
            members = sorted(members, key=lambda i: self.entries[i].sample_id)
            for pos_a in range(len(members)):
                for pos_b in range(pos_a + 1, len(members)):
                    if comparisons >= MAX_TOTAL_COMPARISONS:
                        return (
                            sorted(results, key=lambda t: (-t[2], t[0], t[1]))[
                                :MAX_NEAR_DUP_PAIRS_REPORTED
                            ],
                            comparisons,
                        )
                    a, b = members[pos_a], members[pos_b]
                    ta, tb = self.entries[a].normalized, self.entries[b].normalized
                    if ta == tb:
                        continue  # exact duplicates reported separately
                    id_a = self.entries[a].sample_id
                    id_b = self.entries[b].sample_id
                    canonical = (min(id_a, id_b), max(id_a, id_b))
                    if canonical in seen_pairs:
                        continue
                    seen_pairs.add(canonical)
                    comparisons += 1
                    sim = jaccard_bigrams(ta, tb)
                    if sim >= NEAR_DUP_SIMILARITY_THRESHOLD:
                        results.append((canonical[0], canonical[1], sim))
        results.sort(key=lambda t: (-t[2], t[0], t[1]))
        return results[:MAX_NEAR_DUP_PAIRS_REPORTED], comparisons

    def candidate_bound_facts(self) -> dict[str, object]:
        """Explicit worst-case bound facts exposed via the audit summary."""
        oversized = sum(1 for m in self._buckets.values() if len(m) > MAX_BUCKET_MEMBERS)
        return {
            "max_bucket_members": MAX_BUCKET_MEMBERS,
            "max_total_comparisons": MAX_TOTAL_COMPARISONS,
            "pair_cap_reported": MAX_NEAR_DUP_PAIRS_REPORTED,
            "buckets_skipped_over_cap": oversized,
        }

    def summary(self) -> dict[str, object]:
        pairs, comparisons = self._analyze()
        self.comparisons = comparisons  # mirrors the last (idempotent) analysis
        exact_dup_groups = sum(1 for c in self.exact_counts.values() if c > 1)
        exact_dup_extra = sum(c - 1 for c in self.exact_counts.values() if c > 1)
        return {
            "method": "per-bigram hash bucketing (candidate generation; "
            "buckets over "
            f"{MAX_BUCKET_MEMBERS} members skipped as uninformative) + exact "
            "bigram Jaccard; deterministic and idempotent; worst case "
            "strictly bounded by MAX_TOTAL_COMPARISONS and the bucket-member "
            "cap, NOT mathematically subquadratic in text count and NOT "
            "exhaustive (can miss high-similarity pairs whose shared bigrams "
            "are all ultra-common: documented false negatives); reported "
            "pairs are exact-Jaccard verified (no false positives)",
            "threshold": NEAR_DUP_SIMILARITY_THRESHOLD,
            "min_chars": MIN_NEAR_DUP_CHARS,
            "unique_texts_indexed": len(self.entries),
            "pair_comparisons": comparisons,
            "comparison_budget_exhausted": comparisons >= MAX_TOTAL_COMPARISONS,
            "candidate_bound": self.candidate_bound_facts(),
            "exact_duplicate_groups": exact_dup_groups,
            "exact_duplicate_extra_instances": exact_dup_extra,
            "near_duplicate_pair_count": len(pairs),
            "near_duplicate_pairs_reported": [
                {"id_a": a, "id_b": b, "similarity": round(s, 6)} for a, b, s in pairs
            ],
        }
